
/*
This file was generated by cbintxt at 23:46:16 on 2024-11-21.
cbintxt is freely available at https://github.com/chickenspaceprogram/cbintxt under the Mozilla Public License Version 2.0.
*/

#include "help.h"

void help(FILE *stream) {
    fputs
    (
    "--------------------------------------------------------------------------------\n"
    "POKER RULES\n"
    "--------------------------------------------------------------------------------\n"
    "\n"
    "the rules go here i guess\n"
    "\n"
    ""
    , stream
    );
}
