
/*
This file was generated by cbintxt at 21:49:13 on 2024-11-22.
cbintxt is freely available at https://github.com/chickenspaceprogram/cbintxt under the Mozilla Public License Version 2.0.
*/

#ifndef CBINTXT_HELP_H
#define CBINTXT_HELP_H

#include <stdio.h>

void help(FILE *stream);

#endif
