
/*
This file was generated by cbintxt at 21:49:13 on 2024-11-22.
cbintxt is freely available at https://github.com/chickenspaceprogram/cbintxt under the Mozilla Public License Version 2.0.
*/

#include "help.h"

void help(FILE *stream) {
    fputs
    (
    "\x1b""(0lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk\n"
    "x\x1b""(B                                 \x1b""[1mPOKER RULES\x1b""[22m                                  \x1b""(0x\n"
    "mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj\x1b""(B\n"
    "\n"
    "The goal of Poker is to draw better cards than your opponent, who, in this \n"
    "implementation, is controlled by the computer. To do this, you must draw one of\n"
    "several scoring combinations, listed below in order of precedence, from worst\n"
    "(and most likely) to best (and least likely). \n"
    "\n"
    "If your combination is lower down on the following chart than that of the\n"
    "computer, you win! If you and the dealer have the same combination of cards,\n"
    "you tie, and if your combination is higher on this chart than that of the\n"
    "dealer, you lose.\n"
    "\n"
    "\x1b""(0lqqqqqqqqqqqqqqqqqwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk\n"
    "x\x1b""(B   \x1b""[1mCOMBINATION\x1b""[22m   \x1b""(0x\x1b""(B                        \x1b""[1mDESCRIPTION\x1b""[22m                         \x1b""(0x\n"
    "tqqqqqqqqqqqqqqqqqnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu\n"
    "x\x1b""(B            \x1b""[1mNone\x1b""[22m \x1b""(0x\x1b""(B No scoring combination                                     \x1b""(0x\n"
    "x\x1b""(B            \x1b""[1mPair\x1b""[22m \x1b""(0x\x1b""(B Two cards with the same rank                               \x1b""(0x\n"
    "x\x1b""(B       \x1b""[1mTwo Pairs\x1b""[22m \x1b""(0x\x1b""(B Two Pairs                                                  \x1b""(0x\n"
    "x\x1b""(B \x1b""[1mThree of a kind\x1b""[22m \x1b""(0x\x1b""(B Three cards with the same rank                             \x1b""(0x\n"
    "x\x1b""(B  \x1b""[1mFour of a kind\x1b""[22m \x1b""(0x\x1b""(B Four cards with the same rank                              \x1b""(0x\n"
    "x\x1b""(B      \x1b""[1mFull House\x1b""[22m \x1b""(0x\x1b""(B Three cards with one rank, and two cards with another rank \x1b""(0x\n"
    "x\x1b""(B           \x1b""[1mFlush\x1b""[22m \x1b""(0x\x1b""(B Five cards with the same suit                              \x1b""(0x\n"
    "x\x1b""(B        \x1b""[1mStraight\x1b""[22m \x1b""(0x\x1b""(B Five cards with consecutive ranks                          \x1b""(0x\n"
    "mqqqqqqqqqqqqqqqqqvqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj\x1b""(B\n"
    "\n"
    "You\'ll get one opportunity to redraw up to three cards in hopes of bettering\n"
    "your hand. Be careful, though, you might get unlucky!\n"
    "\n"
    "Press any key to continue . . .\n"
    ""
    , stream
    );
}
